bank:
  base_url: "https://apisandbox.openbankproject.com"
  api_version: 'v2.0.0'
  username: 'sharrona'
  password: "ImpendingD00m!"
  consumer_key: '1hkd22qklce12luoftpblfaalbcj0t2u1ikqddju'
  bank_id: 'op.02.us'
  account: 'bereatest'
